#!/usr/bin/env bash
# install.sh — check / install claude-watcher OS dependencies and git hooks
#
# Safe to re-run.
#
# Usage:
#   bash install.sh               # check deps + set up git hooks (no package install)
#   bash install.sh --install     # install any missing OS deps, then set up git hooks
#   bash install.sh --deps        # check/install deps only (skip git hooks)
#   bash install.sh --hooks       # set up git hooks only (skip dep check)
#
# Note: Neovim plugin dependencies (airline, lualine, etc.) are intentionally
# excluded and must be managed by the user via their Neovim plugin manager.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------
ok()     { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn()   { printf '  \033[33m!\033[0m %s\n' "$*"; }
err()    { printf '  \033[31m✗\033[0m %s\n' "$*" >&2; }
header() { printf '\n\033[1m%s\033[0m\n' "$*"; }

# ---------------------------------------------------------------------------
# OS detection
# ---------------------------------------------------------------------------
is_macos() { [[ "$(uname)" == "Darwin" ]]; }
is_linux() { [[ "$(uname)" == "Linux" ]]; }

# ---------------------------------------------------------------------------
# Dependency check (and optional install)
#
# $1 — "install" to install missing packages; anything else = check only
# ---------------------------------------------------------------------------
check_deps() {
  local do_install=false
  [[ "${1:-}" == "install" ]] && do_install=true

  header "Dependencies"

  local missing=()

  # jq — required for config loading
  if command -v jq &>/dev/null; then
    ok "jq $(jq --version)"
  else
    warn "jq not found"
    missing+=(jq)
  fi

  # Sound player
  if is_macos; then
    if command -v afplay &>/dev/null; then
      ok "afplay (sound)"
    else
      warn "afplay not found (unexpected on macOS)"
    fi
  elif is_linux; then
    if command -v mpg123 &>/dev/null; then
      ok "mpg123 (sound)"
    else
      warn "mpg123 not found"
      missing+=(mpg123)
    fi
  fi

  # OS notifications
  if is_macos; then
    if command -v osascript &>/dev/null; then
      ok "osascript (OS notifications)"
    else
      warn "osascript not found (unexpected on macOS)"
    fi
  elif is_linux; then
    if command -v notify-send &>/dev/null; then
      ok "notify-send (OS notifications)"
    else
      warn "notify-send not found"
      missing+=(libnotify-bin)
    fi
  fi

  # nvim — optional, not installed by this script
  if command -v nvim &>/dev/null; then
    ok "nvim $(nvim --version | head -1) (optional)"
  else
    warn "nvim not found — vim notifications disabled (install via your package manager)"
  fi

  if [[ ${#missing[@]} -eq 0 ]]; then
    return 0
  fi

  if $do_install; then
    header "Installing missing dependencies"
    if is_macos; then
      if command -v brew &>/dev/null; then
        brew install "${missing[@]}" && ok "installed: ${missing[*]}"
      else
        err "Homebrew not found — install missing packages manually: ${missing[*]}"
        return 1
      fi
    elif is_linux; then
      if command -v apt-get &>/dev/null; then
        sudo apt-get install -y "${missing[@]}" && ok "installed: ${missing[*]}"
      else
        err "apt-get not found — install missing packages manually: ${missing[*]}"
        return 1
      fi
    fi
  else
    warn "missing packages: ${missing[*]}"
    warn "re-run with --install to install them automatically"
  fi
}

# ---------------------------------------------------------------------------
# Install git pre-commit hook
#
# Creates .git/hooks/pre-commit as a thin wrapper that calls
# scripts/pre-commit.sh from the repo root, so the actual logic stays
# version-controlled and editable without reinstalling.
# ---------------------------------------------------------------------------
install_hooks() {
  header "Installing git hooks"

  local hooks_dir="$PROJECT_ROOT/.git/hooks"
  local hook_file="$hooks_dir/pre-commit"

  if [[ ! -d "$hooks_dir" ]]; then
    err ".git/hooks directory not found — is this a git repo?"
    return 1
  fi

  # Write the hook wrapper.
  # Runs run-tests.sh --no-vim: syntax (all repo files) + statusline + mock events.
  # The slow headless nvim tests are excluded to keep commits snappy; CI runs the full suite.
  cat > "$hook_file" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by install.sh — do not edit this file directly.
# Edit scripts/run-tests.sh and scripts/pre-commit.sh instead.
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
exec bash "$PROJECT_ROOT/scripts/run-tests.sh" --no-vim
HOOK

  chmod +x "$hook_file"
  ok "installed .git/hooks/pre-commit -> scripts/run-tests.sh --no-vim"
}

# ---------------------------------------------------------------------------
# User config scaffold
# ---------------------------------------------------------------------------
scaffold_user_config() {
  header "User config"

  local user_config_dir="$HOME/.config/claude-watcher"
  local user_config="$user_config_dir/config.json"

  if [[ -f "$user_config" ]]; then
    ok "~/.config/claude-watcher/config.json already exists — not overwriting"
    return 0
  fi

  mkdir -p "$user_config_dir"
  cat > "$user_config" <<'JSON'
{
  "_comment": "User overrides for claude-watcher. Keys here take precedence over config.json in the repo.",
  "_docs": "https://github.com/charlesg3/claude-watcher#configuration"
}
JSON

  ok "created ~/.config/claude-watcher/config.json"
}

# ---------------------------------------------------------------------------
# Log directory
# ---------------------------------------------------------------------------
scaffold_log_dir() {
  local log_dir="$HOME/.local/share/claude-watcher"
  mkdir -p "$log_dir"
  ok "log directory: $log_dir"
}

# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
main() {
  local do_deps=true
  local do_hooks=true
  local do_install=false

  for arg in "$@"; do
    case "$arg" in
      --install) do_install=true ;;
      --deps)    do_hooks=false ;;
      --hooks)   do_deps=false ;;
      -h|--help)
        printf 'Usage: %s [--install] [--deps] [--hooks]\n' "$(basename "$0")"
        printf '  (no flags)   check deps + set up git hooks\n'
        printf '  --install    also install any missing OS packages\n'
        printf '  --deps       dep check/install only (skip git hooks)\n'
        printf '  --hooks      git hooks only (skip dep check)\n'
        exit 0
        ;;
      *)
        printf 'Unknown option: %s\n' "$arg" >&2
        exit 1
        ;;
    esac
  done

  printf '\n\033[1mclaude-watcher install\033[0m\n'

  $do_deps  && check_deps "$($do_install && echo install || echo check)"
  $do_hooks && install_hooks
  scaffold_user_config
  scaffold_log_dir

  printf '\n\033[32mDone.\033[0m\n\n'
  printf 'Next steps:\n'
  printf '  1. Configure hooks in ~/.claude/settings.json (see README.md)\n'
  printf '  2. Edit ~/.config/claude-watcher/config.json to override defaults\n\n'
}

main "$@"
