#!/usr/bin/env bash
# install.sh — set up claude-watcher OS dependencies and git hooks
#
# Safe to re-run. Detects macOS vs Linux and installs what is needed.
#
# Usage:
#   bash install.sh           # install deps + hooks
#   bash install.sh --hooks   # install git hooks only (skip OS deps)
#   bash install.sh --deps    # install OS deps only (skip hooks)

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------
ok()     { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn()   { printf '  \033[33m!\033[0m %s\n' "$*"; }
err()    { printf '  \033[31m✗\033[0m %s\n' "$*" >&2; }
header() { printf '\n\033[1m%s\033[0m\n' "$*"; }

# ---------------------------------------------------------------------------
# OS detection
# ---------------------------------------------------------------------------
is_macos() { [[ "$(uname)" == "Darwin" ]]; }
is_linux() { [[ "$(uname)" == "Linux" ]]; }

# ---------------------------------------------------------------------------
# Dependency checks
# ---------------------------------------------------------------------------
check_deps() {
  header "Checking dependencies"

  local missing=()

  # jq — required for config loading
  if command -v jq &>/dev/null; then
    ok "jq $(jq --version)"
  else
    warn "jq not found"
    missing+=(jq)
  fi

  # Sound player
  if is_macos; then
    if command -v afplay &>/dev/null; then
      ok "afplay (sound)"
    else
      warn "afplay not found (unexpected on macOS)"
    fi
  elif is_linux; then
    if command -v paplay &>/dev/null; then
      ok "paplay (sound)"
    else
      warn "paplay not found"
      missing+=(pulseaudio-utils)
    fi
  fi

  # OS notifications
  if is_macos; then
    if command -v osascript &>/dev/null; then
      ok "osascript (OS notifications)"
    else
      warn "osascript not found (unexpected on macOS)"
    fi
  elif is_linux; then
    if command -v notify-send &>/dev/null; then
      ok "notify-send (OS notifications)"
    else
      warn "notify-send not found"
      missing+=(libnotify-bin)
    fi
  fi

  # nvim — optional
  if command -v nvim &>/dev/null; then
    ok "nvim $(nvim --version | head -1) (optional)"
  else
    warn "nvim not found — vim notifications will be disabled"
  fi

  if [[ ${#missing[@]} -gt 0 ]]; then
    header "Installing missing dependencies"
    if is_macos; then
      if command -v brew &>/dev/null; then
        brew install "${missing[@]}"
        ok "installed: ${missing[*]}"
      else
        err "Homebrew not found. Install missing packages manually: ${missing[*]}"
        return 1
      fi
    elif is_linux; then
      if command -v apt-get &>/dev/null; then
        sudo apt-get install -y "${missing[@]}"
        ok "installed: ${missing[*]}"
      else
        err "apt-get not found. Install missing packages manually: ${missing[*]}"
        return 1
      fi
    fi
  fi
}

# ---------------------------------------------------------------------------
# Install git pre-commit hook
#
# Creates .git/hooks/pre-commit as a thin wrapper that calls
# scripts/pre-commit.sh from the repo root, so the actual logic stays
# version-controlled and editable without reinstalling.
# ---------------------------------------------------------------------------
install_hooks() {
  header "Installing git hooks"

  local hooks_dir="$PROJECT_ROOT/.git/hooks"
  local hook_file="$hooks_dir/pre-commit"

  if [[ ! -d "$hooks_dir" ]]; then
    err ".git/hooks directory not found — is this a git repo?"
    return 1
  fi

  # Write the hook wrapper.
  # Runs run-tests.sh --no-vim: syntax (all repo files) + statusline + mock events.
  # The slow headless nvim tests are excluded to keep commits snappy; CI runs the full suite.
  cat > "$hook_file" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by install.sh — do not edit this file directly.
# Edit scripts/run-tests.sh and scripts/pre-commit.sh instead.
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
exec bash "$PROJECT_ROOT/scripts/run-tests.sh" --no-vim
HOOK

  chmod +x "$hook_file"
  ok "installed .git/hooks/pre-commit -> scripts/run-tests.sh --no-vim"
}

# ---------------------------------------------------------------------------
# User config scaffold
# ---------------------------------------------------------------------------
scaffold_user_config() {
  header "User config"

  local user_config_dir="$HOME/.config/claude-watcher"
  local user_config="$user_config_dir/config.json"

  if [[ -f "$user_config" ]]; then
    ok "~/.config/claude-watcher/config.json already exists — not overwriting"
    return 0
  fi

  mkdir -p "$user_config_dir"
  cat > "$user_config" <<'JSON'
{
  "_comment": "User overrides for claude-watcher. Keys here take precedence over config.json in the repo.",
  "_docs": "https://github.com/charlesg3/claude-watcher#configuration"
}
JSON

  ok "created ~/.config/claude-watcher/config.json"
}

# ---------------------------------------------------------------------------
# Log directory
# ---------------------------------------------------------------------------
scaffold_log_dir() {
  local log_dir="$HOME/.local/share/claude-watcher"
  mkdir -p "$log_dir"
  ok "log directory: $log_dir"
}

# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
main() {
  local do_deps=true
  local do_hooks=true

  for arg in "$@"; do
    case "$arg" in
      --deps)  do_hooks=false ;;
      --hooks) do_deps=false ;;
      -h|--help)
        printf 'Usage: %s [--deps] [--hooks]\n' "$(basename "$0")"
        exit 0
        ;;
      *)
        printf 'Unknown option: %s\n' "$arg" >&2
        exit 1
        ;;
    esac
  done

  printf '\n\033[1mclaude-watcher install\033[0m\n'

  $do_deps  && check_deps
  $do_hooks && install_hooks
  scaffold_user_config
  scaffold_log_dir

  printf '\n\033[32mDone.\033[0m\n\n'
  printf 'Next steps:\n'
  printf '  1. Configure hooks in ~/.claude/settings.json (see README.md)\n'
  printf '  2. Edit ~/.config/claude-watcher/config.json to override defaults\n\n'
}

main "$@"
